name: coveralls
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  report-coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        node-version: [latest]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run lcov
    - run: curl -sL https://coveralls.io/coveralls-linux.tar.gz | tar -xz && ./coveralls report lcov.info
    - run: rm -rf lcov.info
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
