name: coveralls
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  report-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Report Coveralls (Linux)
    - run: curl -sL https://coveralls.io/coveralls-linux.tar.gz | tar -xz && ./coveralls
    - run: npm ci
    - run: node --test --experimental-test-coverage --test-reporter=lcov --test-reporter-destination=test/lcov.info test/index.spec.js
    - run: coveralls report test/lcov.info
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        NODE_ENV: test
